export const ADD_CANVAS_OBJ = "ADD_CANVAS_OBJ";
export const UPDATE_CANVAS_OBJ = "UPDATE_CANVAS_OBJ";
export const DELETE_CANVAS_OBJ = "DELETE_CANVAS_OBJ";
export const CHANGE_ACTIVE = "CHANGE_ACTIVE";
